/**
 * CRA AI Assistant - Excel Generator Service
 * Generates Excel tracker files with clinical trial data
 */

import ExcelJS from 'exceljs';
import * as path from 'path';
import * as fs from 'fs/promises';
import type {
  ExcelExportOptions,
  ExcelExportResult,
  InclusionCriteria,
  ExclusionCriteria,
  VisitSchedule,
  SubjectVisitData,
  MedicationRecord,
} from '@shared/types';
import { ok, err } from '@shared/types/core';
import { ErrorCode, createAppError } from '@shared/types/core';
import { STYLES, COLUMN_WIDTHS, ROW_HEIGHTS } from './styles';
import { EXCEL_SHEET_NAMES } from '@shared/constants';

export class ExcelGenerator {
  private workbook: ExcelJS.Workbook;

  constructor() {
    this.workbook = new ExcelJS.Workbook();
    this.workbook.creator = 'CRA AI Assistant';
    this.workbook.created = new Date();
  }

  /**
   * Set workbook properties
   */
  private setProperties(options: ExcelExportOptions): void {
    this.workbook.properties = {
      creator: options.author || 'CRA AI Assistant',
      title: options.title || '临床试验追踪表',
      subject: options.subject || 'Clinical Trial Tracker',
      keywords: options.keywords || 'CRA,临床试验,追踪表',
      category: options.category || 'Clinical Research',
      comments: options.comments || 'Generated by CRA AI Assistant',
    };
  }

  /**
   * Create inclusion criteria sheet
   */
  private createInclusionCriteriaSheet(criteria: InclusionCriteria[]): void {
    const sheet = this.workbook.addWorksheet(EXCEL_SHEET_NAMES.inclusionCriteria);

    // Set column widths
    sheet.columns = [
      { width: COLUMN_WIDTHS.narrow, key: 'index' },
      { width: COLUMN_WIDTHS.medium, key: 'category' },
      { width: COLUMN_WIDTHS.extraWide, key: 'description' },
    ];

    // Add title
    sheet.mergeCells('A1:C1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = '入选标准 (Inclusion Criteria)';
    titleCell.style = STYLES.title;
    sheet.getRow(1).height = ROW_HEIGHTS.tall;

    // Add header row
    const headerRow = sheet.getRow(3);
    headerRow.values = ['序号', '分类', '标准描述'];
    headerRow.eachCell((cell) => {
      cell.style = STYLES.header;
    });
    headerRow.height = ROW_HEIGHTS.tall;

    // Add data rows
    criteria.forEach((criterion, index) => {
      const row = sheet.getRow(index + 4);
      row.values = [index + 1, criterion.category, criterion.description];
      row.eachCell((cell) => {
        cell.style = index % 2 === 0 ? STYLES.data : STYLES.dataCenter;
      });
    });

    // Freeze header row
    sheet.freezeRows(3);
  }

  /**
   * Create exclusion criteria sheet
   */
  private createExclusionCriteriaSheet(criteria: ExclusionCriteria[]): void {
    const sheet = this.workbook.addWorksheet(EXCEL_SHEET_NAMES.exclusionCriteria);

    // Set column widths
    sheet.columns = [
      { width: COLUMN_WIDTHS.narrow, key: 'index' },
      { width: COLUMN_WIDTHS.medium, key: 'category' },
      { width: COLUMN_WIDTHS.extraWide, key: 'description' },
    ];

    // Add title
    sheet.mergeCells('A1:C1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = '排除标准 (Exclusion Criteria)';
    titleCell.style = STYLES.title;
    sheet.getRow(1).height = ROW_HEIGHTS.tall;

    // Add header row
    const headerRow = sheet.getRow(3);
    headerRow.values = ['序号', '分类', '标准描述'];
    headerRow.eachCell((cell) => {
      cell.style = STYLES.header;
    });
    headerRow.height = ROW_HEIGHTS.tall;

    // Add data rows
    criteria.forEach((criterion, index) => {
      const row = sheet.getRow(index + 4);
      row.values = [index + 1, criterion.category, criterion.description];
      row.eachCell((cell) => {
        cell.style = STYLES.data;
      });
    });

    // Freeze header row
    sheet.freezeRows(3);
  }

  /**
   * Create visit schedule sheet
   */
  private createVisitScheduleSheet(schedule: VisitSchedule[]): void {
    const sheet = this.workbook.addWorksheet(EXCEL_SHEET_NAMES.visitSchedule);

    // Set column widths
    sheet.columns = [
      { width: COLUMN_WIDTHS.medium, key: 'visitType' },
      { width: COLUMN_WIDTHS.medium, key: 'visitDay' },
      { width: COLUMN_WIDTHS.medium, key: 'visitWindow' },
      { width: COLUMN_WIDTHS.wide, key: 'description' },
      { width: COLUMN_WIDTHS.extraWide, key: 'items' },
    ];

    // Add title
    sheet.mergeCells('A1:E1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = '访视计划 (Visit Schedule)';
    titleCell.style = STYLES.title;
    sheet.getRow(1).height = ROW_HEIGHTS.tall;

    // Add header row
    const headerRow = sheet.getRow(3);
    headerRow.values = ['访视名称', '访视时间', '时间窗口', '描述', '检查项目'];
    headerRow.eachCell((cell) => {
      cell.style = STYLES.header;
    });
    headerRow.height = ROW_HEIGHTS.tall;

    // Add data rows
    schedule.forEach((visit, index) => {
      const row = sheet.getRow(index + 4);
      const itemsText = visit.items.map(i => `• ${i.name}${i.required ? '(必查)' : ''}`).join('\n');
      row.values = [
        visit.visitType,
        visit.visitDay,
        visit.visitWindow,
        visit.description,
        itemsText,
      ];
      row.getCell(5).style.alignment = { ...STYLES.data.alignment, wrapText: true };
      row.height = 20 + visit.items.length * 15;
      row.eachCell((cell, colNumber) => {
        if (colNumber < 5) {
          cell.style = STYLES.data;
        }
      });
    });

    // Freeze header row
    sheet.freezeRows(3);
  }

  /**
   * Create subject visits sheet
   */
  private createSubjectVisitsSheet(subjectVisits: SubjectVisitData[]): void {
    const sheet = this.workbook.addWorksheet(EXCEL_SHEET_NAMES.subjectVisits);

    // Set column widths
    sheet.columns = [
      { width: COLUMN_WIDTHS.medium, key: 'subjectId' },
      { width: COLUMN_WIDTHS.medium, key: 'visitType' },
      { width: COLUMN_WIDTHS.medium, key: 'plannedDate' },
      { width: COLUMN_WIDTHS.medium, key: 'actualDate' },
      { width: COLUMN_WIDTHS.narrow, key: 'status' },
      { width: COLUMN_WIDTHS.wide, key: 'notes' },
    ];

    // Add title
    sheet.mergeCells('A1:F1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = '受试者访视记录 (Subject Visits)';
    titleCell.style = STYLES.title;
    sheet.getRow(1).height = ROW_HEIGHTS.tall;

    // Add header row
    const headerRow = sheet.getRow(3);
    headerRow.values = ['受试者编号', '访视名称', '计划日期', '实际日期', '状态', '备注'];
    headerRow.eachCell((cell) => {
      cell.style = STYLES.header;
    });
    headerRow.height = ROW_HEIGHTS.tall;

    // Add data rows
    let rowIndex = 4;
    subjectVisits.forEach((subject) => {
      subject.visits.forEach((visit) => {
        const row = sheet.getRow(rowIndex);
        row.values = [
          subject.subjectId,
          visit.visitType,
          visit.plannedDate,
          visit.actualDate,
          visit.status,
          visit.notes || '',
        ];

        // Style cells
        row.getCell(1).style = STYLES.data;
        row.getCell(2).style = STYLES.data;
        row.getCell(3).style = visit.plannedDate ? STYLES.date : STYLES.data;
        row.getCell(4).style = visit.actualDate ? STYLES.date : STYLES.data;
        row.getCell(5).style = STYLES.dataCenter;
        row.getCell(6).style = STYLES.data;

        rowIndex++;
      });
    });

    // Freeze header row
    sheet.freezeRows(3);
  }

  /**
   * Create medications sheet
   */
  private createMedicationsSheet(medications: MedicationRecord[]): void {
    const sheet = this.workbook.addWorksheet(EXCEL_SHEET_NAMES.medications);

    // Set column widths
    sheet.columns = [
      { width: COLUMN_WIDTHS.medium, key: 'subjectId' },
      { width: COLUMN_WIDTHS.medium, key: 'visitType' },
      { width: COLUMN_WIDTHS.medium, key: 'medicationName' },
      { width: COLUMN_WIDTHS.narrow, key: 'dosage' },
      { width: COLUMN_WIDTHS.medium, key: 'frequency' },
      { width: COLUMN_WIDTHS.narrow, key: 'route' },
      { width: COLUMN_WIDTHS.medium, key: 'startDate' },
      { width: COLUMN_WIDTHS.medium, key: 'endDate' },
      { width: COLUMN_WIDTHS.wide, key: 'notes' },
    ];

    // Add title
    sheet.mergeCells('A1:I1');
    const titleCell = sheet.getCell('A1');
    titleCell.value = '用药记录 (Medication Records)';
    titleCell.style = STYLES.title;
    sheet.getRow(1).height = ROW_HEIGHTS.tall;

    // Add header row
    const headerRow = sheet.getRow(3);
    headerRow.values = ['受试者编号', '访视', '药品名称', '剂量', '频率', '给药途径', '开始日期', '结束日期', '备注'];
    headerRow.eachCell((cell) => {
      cell.style = STYLES.header;
    });
    headerRow.height = ROW_HEIGHTS.tall;

    // Add data rows
    medications.forEach((med, index) => {
      const row = sheet.getRow(index + 4);
      row.values = [
        med.subjectId,
        med.visitType,
        med.medicationName,
        med.dosage,
        med.frequency,
        med.route,
        med.startDate,
        med.endDate,
        med.notes || '',
      ];

      // Style cells
      row.getCell(1).style = STYLES.data;
      row.getCell(2).style = STYLES.data;
      row.getCell(3).style = STYLES.data;
      row.getCell(4).style = STYLES.dataCenter;
      row.getCell(5).style = STYLES.dataCenter;
      row.getCell(6).style = STYLES.dataCenter;
      row.getCell(7).style = STYLES.date;
      row.getCell(8).style = med.endDate ? STYLES.date : STYLES.data;
      row.getCell(9).style = STYLES.data;
    });

    // Freeze header row
    sheet.freezeRows(3);
  }

  /**
   * Generate the Excel file
   */
  async generate(
    data: {
      inclusionCriteria: InclusionCriteria[];
      exclusionCriteria: ExclusionCriteria[];
      visitSchedule: VisitSchedule[];
      subjectVisits: SubjectVisitData[];
      medications: MedicationRecord[];
    },
    options: ExcelExportOptions = {}
  ): Promise<ExcelExportResult> {
    try {
      // Set workbook properties
      this.setProperties(options);

      // Create sheets (only if data exists or includeEmptySheets is true)
      if (data.inclusionCriteria.length > 0 || options.includeEmptySheets) {
        this.createInclusionCriteriaSheet(data.inclusionCriteria);
      }

      if (data.exclusionCriteria.length > 0 || options.includeEmptySheets) {
        this.createExclusionCriteriaSheet(data.exclusionCriteria);
      }

      if (data.visitSchedule.length > 0 || options.includeEmptySheets) {
        this.createVisitScheduleSheet(data.visitSchedule);
      }

      if (data.subjectVisits.length > 0 || options.includeEmptySheets) {
        this.createSubjectVisitsSheet(data.subjectVisits);
      }

      if (data.medications.length > 0 || options.includeEmptySheets) {
        this.createMedicationsSheet(data.medications);
      }

      // Generate output path if not provided
      const outputPath = options.outputPath || path.join(
        process.env.HOME || process.env.USERPROFILE || '.',
        'Downloads',
        options.fileName || `临床试验追踪表_${new Date().toISOString().slice(0, 10)}.xlsx`
      );

      // Ensure directory exists
      const dir = path.dirname(outputPath);
      await fs.mkdir(dir, { recursive: true });

      // Write file
      await this.workbook.xlsx.writeFile(outputPath);

      // Get file stats
      const stats = await fs.stat(outputPath);

      return {
        success: true,
        filePath: outputPath,
        bytesWritten: stats.size,
        sheetCount: this.workbook.worksheets.length,
      };
    } catch (error) {
      return {
        success: false,
        error: `Excel 生成失败: ${error instanceof Error ? error.message : 'Unknown error'}`,
      };
    }
  }

  /**
   * Reset the generator for new file
   */
  reset(): void {
    this.workbook = new ExcelJS.Workbook();
    this.workbook.creator = 'CRA AI Assistant';
    this.workbook.created = new Date();
  }
}

// Singleton instance
let excelGeneratorInstance: ExcelGenerator | null = null;

export const getExcelGenerator = (): ExcelGenerator => {
  if (!excelGeneratorInstance) {
    excelGeneratorInstance = new ExcelGenerator();
  }
  return excelGeneratorInstance;
};
